

about :

  name : "wLookerExtra"
  description : "Collection of light-weight routines to traverse complex data structure. LookerExtra extends Looker by extra routines based on look"
  version : "0.3.26"
  enabled : 1
  interpreters :
  - nodejs >= 6.0.0
  - chrome >= 60.0.0
  - firefox >= 60.0.0
  keywords :
  - wTools

execution :

  scripts :
    test : wtest .run proto/**
    docgen : wdocgen staging

path :

  repository : git+https:///github.com/Wandalen/wLookerExtra.git
  bugs : https:///github.com/Wandalen/wLookerExtra/issues

step :

  export.proto :
    inherit : module.export
    export : path::proto
    tar : 0
    criterion :
      debug : 1
      proto : 1

build :

  proto.export :
    criterion :
      default : 1
      debug : 1
      raw : 1
      proto : 1
      export : 1
      tar : 1
      public : 1
    steps :
      - build::debug.raw
      - step::export.proto

